### ISSUE TITLE
Code blocks are still pretty hard to read.

### ISSUE THREAD

**Issue by joshua-rutherford** [DecipherNow/gm-fabric-documentation#21]
@shanberg, I still find the code blocks a bit hard to read.  I think there should be a balance here between theme and functionality but I'm not the right guy because this whole site would be arial monospace if it were up to me.

**Comment by shanberg** [comment]
@joshua-rutherford Would you mind posting a screenshot of what you're seeing, and perhaps a screenshot of a code block from any other app or documentation that you prefer?

**Comment by chrismholmes** [comment]
Please tell me where I can review the entire site.

**Comment by joshua-rutherford** [comment]
They are much easier to read now @shanberg, it may have been handled by rebasing on master.

**Comment by joshua-rutherford** [comment]
@chrismholmes, pushing the link to you shortly.
