### ISSUE TITLE
Cleanup Headings in Table of Contents

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-documentation#27]
The top level headers should be Overview, Getting Started with Go, and Getting Started with JVM
The links inside of those headers shouldn't have (GO) or (JVM)

![image](https://user-images.githubusercontent.com/8700322/35011172-3dbaddfe-fad3-11e7-9201-3d0d71dde2d4.png)

**Comment by joshua-rutherford** [comment]
That would be awesome but that requires more nesting than is currently supported.  That is, the title shown in the table of contents determines the path of the file thus you run into collisions with identically named titles.

**Comment by spmcbride1201** [comment]
Grrr. This deal is getting worse all the time!
