### ISSUE TITLE
begin moving the README and documentation for the gm-fabric-go repo

### ISSUE THREAD

**Issue by dougfort** [DecipherNow/gm-fabric-documentation#6]
Just a migration of what exists, for now.

I propose to establish the following directory structure (unless @spmcbride1201  has a different one).

```
    content
         |
   _______________
  |             |
jvm             go
                |
       <go applications>
```

**Comment by joshua-rutherford** [comment]
I'm closing this in favor of #9 which provides more details on the intent.
